# Generated by Django 5.2.8 on 2025-12-03 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_crytocurrency_assetrecoveryform_connectwallet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrecoveryform',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('in_review', 'In Review'), ('recovery_mode', 'Recovery Mode Activated')], default='pending review', max_length=15),
        ),
    ]
