# Generated by Django 5.2.8 on 2025-12-04 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_assetrecoveryform_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link_address', models.URLField()),
                ('platform_logo', models.ImageField(blank=True, null=True, upload_to='platform_logos/')),
            ],
        ),
        migrations.AlterField(
            model_name='assetrecoveryform',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('in_review', 'In Review'), ('recovery_mode', 'Recovery Activated')], default='pending review', max_length=15),
        ),
    ]
