# Generated by Django 5.0.1 on 2025-12-04 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cryptoplatform_alter_assetrecoveryform_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('daily_interest_rate', models.DecimalField(decimal_places=2, help_text='Percentage per day (e.g., 2.5 for 2.5%)', max_digits=5)),
                ('duration_days', models.IntegerField(help_text='Investment duration in days')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_invested', models.DecimalField(decimal_places=8, help_text='Amount in crypto units', max_digits=20)),
                ('amount_in_usd', models.DecimalField(decimal_places=2, help_text='USD value at time of investment', max_digits=20)),
                ('daily_profit', models.DecimalField(decimal_places=2, default=0, help_text='Daily profit in USD', max_digits=20)),
                ('total_profit_earned', models.DecimalField(decimal_places=2, default=0, help_text='Total accumulated profit in USD', max_digits=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('last_profit_date', models.DateTimeField(blank=True, null=True)),
                ('cryptocurrency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.crytocurrency')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.investmentplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('investment_start', 'Investment Start'), ('daily_profit', 'Daily Profit'), ('final_payout', 'Final Payout')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in USD', max_digits=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.userinvestment')),
            ],
        ),
    ]
