# Generated by Django 5.0.1 on 2025-12-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_creditcardtype_creditcardrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcardrequest',
            name='card_number',
            field=models.CharField(blank=True, help_text='Format: XXXX XXXX XXXX XXXX', max_length=19, null=True),
        ),
        migrations.AddField(
            model_name='creditcardrequest',
            name='cvv',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='creditcardrequest',
            name='expiry_date',
            field=models.CharField(blank=True, help_text='Format: MM/YY', max_length=5, null=True),
        ),
    ]
