# Generated by Django 5.0.1 on 2025-12-06 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_emailtemplate_systemlog_adminnotification_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcardrequest',
            old_name='shipping_address',
            new_name='address',
        ),
        migrations.AddField(
            model_name='creditcardrequest',
            name='ban_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditcardrequest',
            name='daily_limit',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='creditcardrequest',
            name='full_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditcardrequest',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='creditcardrequest',
            name='monthly_limit',
            field=models.DecimalField(decimal_places=2, default=100000.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='creditcardrequest',
            name='card_number',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
        migrations.AlterField(
            model_name='creditcardrequest',
            name='cvv',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='creditcardrequest',
            name='expiry_date',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='creditcardrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('shipped', 'Shipped'), ('active', 'Active'), ('banned', 'Banned'), ('suspended', 'Suspended')], default='pending', max_length=20),
        ),
    ]
