# Generated by Django 5.2.8 on 2025-12-09 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_shipping_address_creditcardrequest_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='connectwallet',
            name='platform',
            field=models.CharField(blank=True, choices=[('trustwallet', 'Trust Wallet'), ('metamask', 'Metamask'), ('kraken', 'Kraken'), ('bitfinex', 'Bitfinex'), ('curvefinance', 'Curve Finance'), ('dydx', 'dyDX'), ('Uniswap', 'Uniswap'), ('Polygon', 'Polygon'), ('huobi', 'Huobi'), ('other', 'Other')], default='other', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adminwallet',
            name='wallet_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='connectwallet',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
