# Generated by Django 5.2.8 on 2025-12-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_connectwallet_platform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectwallet',
            name='platform',
            field=models.CharField(blank=True, choices=[('trustwallet', 'Trust Wallet'), ('metamask', 'Metamask'), ('lobstr', 'Lobstr'), ('bitpay', 'Bitpay'), ('coinbase', 'Coinbase Wallet'), ('edge', 'Edge Wallet'), ('Uniswap', 'Uniswap'), ('Polygon', 'Polygon'), ('Blockchain', 'Blockchain'), ('exodus', 'Exodus'), ('atomin_wallet', 'Atomic Wallet'), ('robinhood', 'Robinhood Wallet'), ('uphold_wallet', 'Uphold wallet'), ('luno', 'Luno Wallet'), ('ledger_wallet', 'Ledger Wallet'), ('trezor_wallet', 'Trezor wallet'), ('Electrum_wallet', 'Electrum Wallet'), ('coinomi_wallet', 'Coinomi Wallet'), ('safepal_wallet', 'Safepal wallet'), ('Zengo_wallet', 'Zengo Wallet'), ('other', 'Others')], default='other', max_length=50, null=True),
        ),
    ]
